databases:
  - name: Runteq_portfolio_DB
    databaseName: runteq_portfolio_db_hdqi
    user: Runteq_portfolio
    region: singapore

services:
  - type: web
    name: Runteq_portfolio
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Runteq_portfolio_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: GMAIL_USERNAME
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: RENDER_EXTERNAL_HOSTNAME
        sync: false