name: Ruby on Rails CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      POSTGRES_PASSWORD: password
      DATABASE_URL: postgres://postgres:password@localhost:5432/portfolio_app_test

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.2
        bundler-cache: true

    - name: Install PostgreSQL client
      run: |
        sudo apt-get update
        sudo apt-get install -y libpq-dev

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '19'

    - name: Install Yarn
      run: npm install -g yarn

    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.OS }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-yarn-

    - name: Install dependencies
      run: |
        gem install bundler
        bundle config set path 'vendor/bundle'
        bundle install --jobs 4 --retry 3
        yarn install

    - name: Setup database
      run: |
        bundle exec rails db:create
        bundle exec rails db:schema:load
<<<<<<< HEAD

    - name: Run RSpec tests
      run: bundle exec rspec

    - name: Run system tests
      run: bundle exec rspec spec/system
=======
    - name: Run tests
      env:
        RAILS_ENV: test
        POSTGRES_PASSWORD: postgres
>>>>>>> d3a3c28a20710b58d24f729f5ad48c71a1470f97
